version: '3.5'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_db:/var/lib/postgresql/dat+-/8-*]

volumes:
  my_postgres_db: